version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discordboto
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  backend:
    build: ./apps/backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app/apps/backend
  frontend:
    build: ./apps/frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app/apps/frontend
volumes:
  db_data:
